### ISSUE TITLE
Class 'API' not found

### ISSUE THREAD

**Issue by pehser** [yandex-money/yandex-money-sdk-php#12]
require_once __DIR__ .'/../ym_new/lib/api.php';
    require_once __DIR__ . '/../ym_new/lib/external_payment.php';
    $auth_url = API::buildObtainTokenUrl( $client_id, $redirect_uri, $scope );

в результате
Class 'API' not found
как исправить?
p.s
php 5.3.8

**Comment by nywuctuk** [comment]
попробуй добавить:
use \YandexMoney\API;

если не помогло, смотри загруженные классы:
echo '<pre>';
print_r(get_declared_classes());
echo '</pre>';

**Comment by raymank26** [comment]
Да, так. Поправил README.
