### ISSUE TITLE
ERROR: Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by nywuctuk** [yandex-money/yandex-money-sdk-php#14]
Recoverable error
Object of class stdClass could not be converted to string

На 4 этапе  при использовании объекта $api
$api->accountInfo();
или
$api->requestPayment(...);

http://s020.radikal.ru/i702/1501/65/2ee52b1fee7a.jpg

**Comment by raymank26** [comment]
После получения токена, нужно проверить статус и взять свойство `access_token` у полученного объекта. Поправил документацию, было не совсем верно.
