### ISSUE TITLE
не работает тестовый платеж

### ISSUE THREAD

**Issue by nywuctuk** [yandex-money/yandex-money-sdk-php#15]
Пробую оплатить я. кошельком, перевод идет на другой я. кошелек.
Ошибки:
1) если на счету 0 (пополнил)
2) если нет персональных данных (ввел)
(тут ext_action_uri = https://sp-money.yandex.ru/idlight.xml)

3) теперь ошибка $process_payment->error = "contract_not_found" (как для тестового, так и для обычного)

**Comment by raymank26** [comment]
Не совсем понятно в чем проблема. Можно более подробное описание?

**Comment by nywuctuk** [comment]
https://tech.yandex.ru/money/doc/dg/reference/process-payment-docpage/
http://i008.radikal.ru/1501/44/c2007bc8a517.jpg

это вы должны дать более подробное описание этой ошибки или как с ней бороться))

**Comment by raymank26** [comment]
Попробуйте написать на https://money.yandex.ru/feedback/ c точным описанием ошибки(полным текстом ответов).

**Comment by nywuctuk** [comment]
да уже.. 
что полезного кроме $process_payment->error я еще могу вывести?
больше информации нет..

**Comment by nywuctuk** [comment]
Разобрался с 3им пунктом - присваивал пустое значение параметру request_id в process-payment. Видимо описание ошибки "ОТСУТСТВУЕТ ВЫСТАВЛЕННЫЙ КОНТРАКТ..."  навел на мысль, что это внешняя ошибка, а не внутренняя.

Платеж произошел успешно и по настоящему, что подтверждает название топика - ТЕСТОВЫЙ платеж НЕ работает.
Передаю эти параметры как в requestPayment, так и в processPayment.
$options['test_payment'] 	= 	true;
$options['test_card'] 		= 	'available';
$options['test_result'] 	= 	'success';

**Comment by nywuctuk** [comment]
<b>Ответ разработчиков:</b>
Параметр "test_payment" следует указывает как "true". Дело в том, что в PHP в обратном случае на сервер передается "1" вместо строки "true". Этот случай описан в разделе Side notes github.com/yandex-money/yandex-money-sdk-php#side-notes
